name: SonarQube scan

runs:
  using: "composite"
  steps:
    - name: Initialize or restore NPM cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      run: npm ci
      shell: bash
